import type { BuyerOrder } from "../../types/orders"

export const useBuyerOrders = () => {
  const orders = ref<BuyerOrder[]>([
    {
      id: "ord-240417-118",
      orderNumber: "ORD-240417-118",
      seller: "Studio Mộc",
      placedAt: "17/04/2026 · 09:20",
      status: "pending",
      deliveryWindow: "Shop dự kiến xác nhận trong 2 giờ",
      paymentMethod: "Ví VNSEEA",
      paymentStatus: "paid",
      paymentReference: "VNSEEA-PAY-240417118",
      recipientName: "Tiến Đặng",
      recipientPhone: "0939 269 376",
      shippingAddress: "Tầng 8, 18 Nguyễn Chí Thanh, Đống Đa, Hà Nội",
      shippingProvider: "VNSEEA Express",
      trackingCode: "VNS-118-240417",
      note: "Gọi trước khi giao trong giờ hành chính.",
      shippingFee: 0,
      total: 1780000,
      items: [
        {
          id: "i-1",
          name: "Loa bluetooth mini",
          quantity: 1,
          price: 890000,
          imageStyle: [
            "radial-gradient(circle at 78% 12%, rgba(255,214,182,0.42), transparent 18%)",
            "radial-gradient(circle at 20% 20%, rgba(255,255,255,0.24), transparent 22%)",
            "linear-gradient(150deg, #111827 0%, #4f46e5 42%, #c4b5fd 100%)",
          ].join(", "),
        },
        {
          id: "i-2",
          name: "Tai nghe chống ồn",
          quantity: 1,
          price: 890000,
          imageStyle: [
            "radial-gradient(circle at 75% 16%, rgba(255,255,255,0.26), transparent 20%)",
            "linear-gradient(140deg, #243b63 0%, #6c8de2 44%, #dbeafe 100%)",
          ].join(", "),
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Đã tạo đơn",
          time: "17/04/2026 · 09:20",
          description: "Đơn hàng được ghi nhận và chờ shop xác nhận.",
          done: true,
        },
        {
          key: "confirmed",
          label: "Shop xác nhận",
          time: "Đang chờ",
          description: "Shop sẽ kiểm tra tồn kho và chuẩn bị đơn của bạn.",
          done: false,
        },
        {
          key: "shipping",
          label: "Bàn giao vận chuyển",
          time: "Đang chờ",
          description: "Đơn sẽ được chuyển sang đơn vị giao hàng sau khi xác nhận.",
          done: false,
        },
        {
          key: "completed",
          label: "Giao thành công",
          time: "Đang chờ",
          description: "Bạn sẽ nhận được thông báo khi đơn hoàn tất.",
          done: false,
        },
      ],
    },
    {
      id: "ord-240416-083",
      orderNumber: "ORD-240416-083",
      seller: "Nông trại Bơ",
      placedAt: "16/04/2026 · 15:40",
      status: "shipping",
      deliveryWindow: "Dự kiến giao hôm nay trước 17:30",
      paymentMethod: "Ví VNSEEA",
      paymentStatus: "paid",
      paymentReference: "VNSEEA-PAY-240416083",
      recipientName: "Tiến Đặng",
      recipientPhone: "0939 269 376",
      shippingAddress: "12 Trần Hưng Đạo, Hải Châu, Đà Nẵng",
      shippingProvider: "VNSEEA Fast",
      trackingCode: "VNS-083-240416",
      note: "Ưu tiên giao trước 17:30 vì người nhận có lịch họp.",
      shippingFee: 15000,
      total: 435000,
      items: [
        {
          id: "i-3",
          name: "Hạt điều rang muối 500g",
          quantity: 1,
          price: 210000,
          imageStyle: [
            "radial-gradient(circle at 78% 12%, rgba(255,214,182,0.36), transparent 18%)",
            "linear-gradient(150deg, #7c2d12 0%, #ea580c 40%, #fdba74 100%)",
          ].join(", "),
        },
        {
          id: "i-4",
          name: "Mật ong rừng nguyên chất",
          quantity: 1,
          price: 210000,
          imageStyle: [
            "radial-gradient(circle at 24% 18%, rgba(255,255,255,0.28), transparent 18%)",
            "linear-gradient(140deg, #713f12 0%, #f59e0b 48%, #fde68a 100%)",
          ].join(", "),
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Đã tạo đơn",
          time: "16/04/2026 · 15:40",
          description: "Đơn hàng được ghi nhận thành công trên hệ thống.",
          done: true,
        },
        {
          key: "confirmed",
          label: "Shop xác nhận",
          time: "16/04/2026 · 16:10",
          description: "Shop đã xác nhận tồn kho và đóng gói đơn hàng.",
          done: true,
        },
        {
          key: "shipping",
          label: "Đang vận chuyển",
          time: "17/04/2026 · 08:25",
          description: "Đơn đang trên xe giao và sẽ đến trong hôm nay.",
          done: true,
        },
        {
          key: "completed",
          label: "Giao thành công",
          time: "Chưa hoàn tất",
          description: "Bước này sẽ hoàn tất khi bạn nhận đủ hàng.",
          done: false,
        },
      ],
    },
    {
      id: "ord-240411-051",
      orderNumber: "ORD-240411-051",
      seller: "Hoàng An Decor",
      placedAt: "11/04/2026 · 11:05",
      status: "delivered",
      deliveryWindow: "Đã giao thành công ngày 13/04/2026",
      paymentMethod: "Ví VNSEEA",
      paymentStatus: "paid",
      paymentReference: "VNSEEA-PAY-240411051",
      recipientName: "Tiến Đặng",
      recipientPhone: "0939 269 376",
      shippingAddress: "36 Xuân Diệu, Tây Hồ, Hà Nội",
      shippingProvider: "VNSEEA Home",
      trackingCode: "VNS-051-240411",
      note: "Người nhận đã kiểm tra hàng và xác nhận đủ phụ kiện.",
      shippingFee: 0,
      total: 1850000,
      items: [
        {
          id: "i-5",
          name: "Bàn trà gỗ sồi",
          quantity: 1,
          price: 1850000,
          imageStyle: [
            "radial-gradient(circle at 76% 10%, rgba(255,255,255,0.22), transparent 18%)",
            "linear-gradient(150deg, #78350f 0%, #b45309 38%, #f59e0b 100%)",
          ].join(", "),
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Đã tạo đơn",
          time: "11/04/2026 · 11:05",
          description: "Đơn được ghi nhận thành công.",
          done: true,
        },
        {
          key: "confirmed",
          label: "Shop xác nhận",
          time: "11/04/2026 · 11:46",
          description: "Shop bắt đầu chuẩn bị và đóng gói hàng.",
          done: true,
        },
        {
          key: "shipping",
          label: "Đang vận chuyển",
          time: "12/04/2026 · 08:15",
          description: "Đơn hàng được bàn giao cho đơn vị vận chuyển.",
          done: true,
        },
        {
          key: "completed",
          label: "Giao thành công",
          time: "13/04/2026 · 14:32",
          description: "Người mua đã nhận hàng và đơn hoàn tất.",
          done: true,
        },
      ],
    },
    {
      id: "ord-240406-019",
      orderNumber: "ORD-240406-019",
      seller: "Beauty Lab",
      placedAt: "06/04/2026 · 08:50",
      status: "cancelled",
      deliveryWindow: "Đơn đã hủy theo yêu cầu của người mua",
      paymentMethod: "Hoàn về ví VNSEEA",
      paymentStatus: "refunded",
      paymentReference: "VNSEEA-RF-240406019",
      recipientName: "Tiến Đặng",
      recipientPhone: "0939 269 376",
      shippingAddress: "92 Lê Lợi, Ninh Kiều, Cần Thơ",
      shippingProvider: "VNSEEA Express",
      trackingCode: "Không áp dụng",
      note: "Người mua đã đổi nhu cầu và yêu cầu hủy trước khi shop bàn giao.",
      shippingFee: 0,
      total: 520000,
      items: [
        {
          id: "i-6",
          name: "Combo dưỡng tóc Yaskey",
          quantity: 1,
          price: 520000,
          imageStyle: [
            "radial-gradient(circle at 24% 18%, rgba(255,255,255,0.3), transparent 18%)",
            "linear-gradient(140deg, #0f766e 0%, #14b8a6 45%, #99f6e4 100%)",
          ].join(", "),
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Đã tạo đơn",
          time: "06/04/2026 · 08:50",
          description: "Đơn được ghi nhận thành công.",
          done: true,
        },
        {
          key: "cancelled",
          label: "Yêu cầu hủy đơn",
          time: "06/04/2026 · 09:15",
          description: "Người mua gửi yêu cầu hủy trước khi đơn được xác nhận.",
          done: true,
        },
        {
          key: "refunded",
          label: "Hoàn tiền về ví",
          time: "06/04/2026 · 09:48",
          description: "Tiền đã được hoàn về ví nội bộ VNSEEA.",
          done: true,
        },
      ],
    },
  ])

  const findOrderById = (orderId: string) =>
    orders.value.find(order => order.id === orderId) ?? null

  return {
    orders,
    findOrderById,
  }
}
