import type { SellerOrder } from "../../types/orders"

export const useSellerOrders = () => {
  const orders = ref<SellerOrder[]>([
    {
      id: "sale-240417-301",
      orderNumber: "SALE-240417-301",
      storeName: "Mộc Mây Studio",
      buyerName: "Ngọc Trâm",
      buyerPhone: "0901 223 445",
      buyerAddress: "128 Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
      placedAt: "17/04/2026 · 10:15",
      status: "pending",
      deliveryWindow: "Cần xác nhận đơn trước 13:00 hôm nay",
      paymentMethod: "Ví VNSEEA",
      paymentStatus: "paid",
      paymentReference: "VNSEEA-SALE-240417301",
      shippingProvider: "VNSEEA Express",
      trackingCode: "Đang chờ tạo",
      buyerNote: "Nhờ shop gói kỹ phần mặt kính và gọi trước khi giao.",
      sellerNote: "Kiểm tra lại phụ kiện lắp ráp và phiếu bảo hành trước khi đóng gói.",
      shippingFee: 30000,
      total: 2430000,
      payoutStatus: "queued",
      payoutAmount: 2400000,
      payoutReference: "PAYOUT-240417301",
      payoutWindow: "Đối soát sau khi khách xác nhận nhận hàng 24 giờ",
      items: [
        {
          id: "s-1",
          name: "Bàn console gỗ sồi",
          quantity: 1,
          price: 2150000,
          imageStyle: [
            "radial-gradient(circle at 72% 12%, rgba(255,237,213,0.4), transparent 18%)",
            "linear-gradient(140deg, #422006 0%, #a16207 42%, #facc15 100%)",
          ].join(", "),
        },
        {
          id: "s-2",
          name: "Bộ phụ kiện treo tường",
          quantity: 1,
          price: 250000,
          imageStyle: [
            "radial-gradient(circle at 20% 18%, rgba(255,255,255,0.28), transparent 18%)",
            "linear-gradient(150deg, #1f2937 0%, #64748b 40%, #dbeafe 100%)",
          ].join(", "),
        },
      ],
      tasks: [
        {
          key: "payment",
          label: "Đã xác thực thanh toán",
          description: "Ví nội bộ đã ghi nhận thành công, có thể bắt đầu xử lý đơn.",
          done: true,
        },
        {
          key: "stock",
          label: "Kiểm tra tồn kho và phụ kiện",
          description: "Đảm bảo hàng đủ số lượng, phụ kiện và tình trạng đóng gói.",
          done: true,
        },
        {
          key: "packing",
          label: "Đóng gói và in vận đơn",
          description: "Cần hoàn tất trước khi bàn giao cho đơn vị vận chuyển.",
          done: false,
        },
        {
          key: "handoff",
          label: "Bàn giao cho shipper",
          description: "Hệ thống sẽ mở đối soát sau khi đơn được quét ra khỏi kho.",
          done: false,
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Khách đã đặt hàng",
          time: "17/04/2026 · 10:15",
          description: "Đơn hàng được khách tạo thành công và đã thanh toán qua ví VNSEEA.",
          done: true,
        },
        {
          key: "pending",
          label: "Chờ shop xác nhận",
          time: "Đang diễn ra",
          description: "Bạn cần xác nhận tình trạng hàng và chuẩn bị trước khi tạo vận đơn.",
          done: false,
        },
        {
          key: "shipping",
          label: "Chờ bàn giao vận chuyển",
          time: "Đang chờ",
          description: "Bước này hoàn tất khi shop in nhãn và giao cho đơn vị vận chuyển.",
          done: false,
        },
        {
          key: "completed",
          label: "Chờ khách nhận hàng",
          time: "Đang chờ",
          description: "Sau khi giao thành công, đối soát sẽ được mở cho shop.",
          done: false,
        },
      ],
    },
    {
      id: "sale-240416-188",
      orderNumber: "SALE-240416-188",
      storeName: "VNSEEA Mobility Lab",
      buyerName: "Minh Anh",
      buyerPhone: "0988 145 678",
      buyerAddress: "42 Phạm Ngọc Thạch, Đống Đa, Hà Nội",
      placedAt: "16/04/2026 · 16:05",
      status: "shipping",
      deliveryWindow: "Đơn đã rời kho, dự kiến giao trong ngày",
      paymentMethod: "Ví VNSEEA",
      paymentStatus: "paid",
      paymentReference: "VNSEEA-SALE-240416188",
      shippingProvider: "VNSEEA Fast",
      trackingCode: "FAST-188-240416",
      buyerNote: "Khách cần xuất phiếu giao hàng đi kèm đơn.",
      sellerNote: "Đã bàn giao bưu tá lúc 08:30, chờ cập nhật quét giao.",
      shippingFee: 20000,
      total: 980000,
      payoutStatus: "processing",
      payoutAmount: 960000,
      payoutReference: "PAYOUT-240416188",
      payoutWindow: "Đối soát trong 24-48 giờ sau khi giao thành công",
      items: [
        {
          id: "s-3",
          name: "Combo phụ kiện sạc nhanh",
          quantity: 2,
          price: 480000,
          imageStyle: [
            "radial-gradient(circle at 72% 12%, rgba(255,255,255,0.24), transparent 18%)",
            "linear-gradient(140deg, #0f172a 0%, #2563eb 42%, #7dd3fc 100%)",
          ].join(", "),
        },
      ],
      tasks: [
        {
          key: "payment",
          label: "Đã xác thực thanh toán",
          description: "Tiền đã về hệ thống và chờ đối soát sau khi hoàn tất giao.",
          done: true,
        },
        {
          key: "stock",
          label: "Đã xác nhận hàng đủ",
          description: "Kho đã giữ đủ hàng cho đơn này.",
          done: true,
        },
        {
          key: "packing",
          label: "Đã đóng gói và dán nhãn",
          description: "Đơn đã được chuẩn hóa theo quy cách vận chuyển.",
          done: true,
        },
        {
          key: "handoff",
          label: "Đã bàn giao đơn vị giao hàng",
          description: "Chờ cập nhật quét giao và trạng thái giao thành công.",
          done: true,
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Khách đặt hàng",
          time: "16/04/2026 · 16:05",
          description: "Đơn được tạo thành công trong marketplace.",
          done: true,
        },
        {
          key: "confirmed",
          label: "Shop xác nhận đơn",
          time: "16/04/2026 · 16:34",
          description: "Shop xác nhận tồn kho và bắt đầu xử lý đơn.",
          done: true,
        },
        {
          key: "shipping",
          label: "Đang vận chuyển",
          time: "17/04/2026 · 08:30",
          description: "Đơn đã được quét ra khỏi kho và đang trên đường tới khách.",
          done: true,
        },
        {
          key: "completed",
          label: "Chờ giao thành công",
          time: "Đang chờ",
          description: "Sau khi khách xác nhận nhận hàng, đối soát sẽ được hoàn tất.",
          done: false,
        },
      ],
    },
    {
      id: "sale-240411-074",
      orderNumber: "SALE-240411-074",
      storeName: "Học Nhanh Mỗi Ngày",
      buyerName: "Phương Linh",
      buyerPhone: "0912 005 223",
      buyerAddress: "85 Võ Văn Tần, Quận 3, TP.HCM",
      placedAt: "11/04/2026 · 09:12",
      status: "delivered",
      deliveryWindow: "Khách đã nhận đơn ngày 13/04/2026",
      paymentMethod: "Ví VNSEEA",
      paymentStatus: "paid",
      paymentReference: "VNSEEA-SALE-240411074",
      shippingProvider: "VNSEEA Home",
      trackingCode: "HOME-074-240411",
      buyerNote: "Khách xác nhận nhận đủ tài liệu và quà tặng kèm.",
      sellerNote: "Đơn hoàn tất, chờ chốt báo cáo cuối ngày cho bộ phận vận hành.",
      shippingFee: 0,
      total: 1260000,
      payoutStatus: "released",
      payoutAmount: 1260000,
      payoutReference: "PAYOUT-240411074",
      payoutWindow: "Đã ghi có vào ngân quỹ cửa hàng ngày 14/04/2026",
      items: [
        {
          id: "s-4",
          name: "Bộ tài liệu workshop leadership",
          quantity: 1,
          price: 1260000,
          imageStyle: [
            "radial-gradient(circle at 20% 18%, rgba(255,255,255,0.24), transparent 18%)",
            "linear-gradient(140deg, #164e63 0%, #0f766e 45%, #a7f3d0 100%)",
          ].join(", "),
        },
      ],
      tasks: [
        {
          key: "payment",
          label: "Thanh toán hợp lệ",
          description: "Giao dịch đã khớp và được chấp nhận đối soát.",
          done: true,
        },
        {
          key: "stock",
          label: "Đã hoàn tất xử lý đơn",
          description: "Kho và vận hành đã xác nhận đơn đúng cấu hình yêu cầu.",
          done: true,
        },
        {
          key: "packing",
          label: "Đã hoàn tất đóng gói",
          description: "Đơn được bàn giao đúng quy chuẩn và đúng thời gian.",
          done: true,
        },
        {
          key: "handoff",
          label: "Đối soát đã hoàn tất",
          description: "Tiền đã về ví/ngân quỹ của shop.",
          done: true,
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Khách đặt hàng",
          time: "11/04/2026 · 09:12",
          description: "Đơn được hệ thống ghi nhận thành công.",
          done: true,
        },
        {
          key: "confirmed",
          label: "Shop xác nhận và đóng gói",
          time: "11/04/2026 · 10:02",
          description: "Shop xác nhận hàng và chuyển sang bước đóng gói.",
          done: true,
        },
        {
          key: "shipping",
          label: "Bàn giao vận chuyển",
          time: "12/04/2026 · 08:10",
          description: "Đơn được bàn giao cho đối tác giao nhận.",
          done: true,
        },
        {
          key: "completed",
          label: "Khách nhận hàng thành công",
          time: "13/04/2026 · 15:26",
          description: "Khách nhận đủ hàng, đơn hoàn tất và được đối soát cho shop.",
          done: true,
        },
      ],
    },
    {
      id: "sale-240406-029",
      orderNumber: "SALE-240406-029",
      storeName: "Beauty Lab",
      buyerName: "Khánh Vân",
      buyerPhone: "0934 115 990",
      buyerAddress: "22 Lê Hồng Phong, Nha Trang",
      placedAt: "06/04/2026 · 08:20",
      status: "cancelled",
      deliveryWindow: "Đơn đã hủy trước khi bàn giao vận chuyển",
      paymentMethod: "Hoàn về ví VNSEEA",
      paymentStatus: "refunded",
      paymentReference: "VNSEEA-RF-240406029",
      shippingProvider: "VNSEEA Express",
      trackingCode: "Không áp dụng",
      buyerNote: "Khách đổi mẫu sản phẩm và yêu cầu hủy sớm.",
      sellerNote: "Đơn dừng xử lý, hàng được trả lại tồn kho.",
      shippingFee: 0,
      total: 520000,
      payoutStatus: "reversed",
      payoutAmount: 0,
      payoutReference: "PAYOUT-240406029",
      payoutWindow: "Không đối soát do giao dịch đã hoàn tiền",
      items: [
        {
          id: "s-5",
          name: "Combo dưỡng tóc Yaskey",
          quantity: 1,
          price: 520000,
          imageStyle: [
            "radial-gradient(circle at 24% 18%, rgba(255,255,255,0.3), transparent 18%)",
            "linear-gradient(140deg, #0f766e 0%, #14b8a6 45%, #99f6e4 100%)",
          ].join(", "),
        },
      ],
      tasks: [
        {
          key: "payment",
          label: "Hoàn tác thanh toán",
          description: "Khoản tiền đã được hoàn về ví của người mua.",
          done: true,
        },
        {
          key: "stock",
          label: "Trả hàng về tồn kho",
          description: "Sản phẩm không còn bị giữ cho đơn này.",
          done: true,
        },
        {
          key: "packing",
          label: "Dừng quy trình đóng gói",
          description: "Không tiếp tục tạo vận đơn hoặc bàn giao vận chuyển.",
          done: true,
        },
        {
          key: "handoff",
          label: "Đóng hồ sơ đơn hủy",
          description: "Lưu lại ghi chú nội bộ và nguyên nhân hủy đơn.",
          done: true,
        },
      ],
      timeline: [
        {
          key: "created",
          label: "Khách đặt hàng",
          time: "06/04/2026 · 08:20",
          description: "Đơn hàng được tạo thành công.",
          done: true,
        },
        {
          key: "cancelled",
          label: "Khách yêu cầu hủy",
          time: "06/04/2026 · 08:44",
          description: "Khách thay đổi nhu cầu trước khi shop xác nhận xử lý.",
          done: true,
        },
        {
          key: "refunded",
          label: "Hoàn tiền & đóng đơn",
          time: "06/04/2026 · 09:05",
          description: "Hệ thống hoàn tiền về ví và đóng hồ sơ đơn hàng.",
          done: true,
        },
      ],
    },
  ])

  const findOrderById = (orderId: string) =>
    orders.value.find(order => order.id === orderId) ?? null

  return {
    orders,
    findOrderById,
  }
}
