const encodeSegment = (value: string | number) => encodeURIComponent(String(value))
const encodeQueryValue = (value: string | number) => encodeURIComponent(String(value))

export const appRoutes = {
  home: "/",
  feed: "/home",
  adminCp: "/admin-cp",
  welcome: "/welcome",
  register: "/register",
  forgotPassword: "/forgot-password",
  confirmLogin: "/confirm-login",
  resetPassword: "/reset-password",
  confirmAccount: "/confirm-account",
  confirmResetSms: "/confirm-reset-sms",
  logout: "/logout",
  explore: "/explore",
  hashtag: (tag: string) => `/hashtag/${encodeSegment(tag)}`,
  blogs: "/blogs",
  createBlog: "/create-blog",
  readBlog: (slug: string) => `/read-blog/${encodeSegment(slug)}`,
  popular: "/popular",
  savedPosts: "/saved-posts",
  reels: "/reels",
  watch: "/watch",
  photos: "/photos",
  movies: "/movies",
  memories: "/memories",
  search: "/search",
  statusCreate: "/status/create",
  products: "/products",
  newProduct: "/new-product",
  editProduct: (id: string | number) => `/edit-product/${encodeSegment(id)}`,
  myProducts: "/my-products",
  directory: "/directory",
  forum: "/forum",
  games: "/games",
  goPro: "/go-pro",
  live: "/live",
  poke: "/poke",
  checkout: "/checkout",
  orders: "/orders",
  orderDetail: (id: string | number) => `/order/${encodeSegment(id)}`,
  customerOrder: (id: string | number) => `/customer_order/${encodeSegment(id)}`,
  jobs: "/jobs",
  funding: "/funding",
  createFunding: "/create_funding",
  showFund: (id: string | number) => `/show_fund/${encodeSegment(id)}`,
  events: "/events",
  createEvent: "/events/create-event",
  eventDetail: (id: string | number) => `/events/${encodeSegment(id)}`,
  groups: "/groups",
  suggestedGroups: "/suggested-groups",
  joinedGroups: "/joined_groups",
  createGroup: "/create-group",
  groupDetail: (name: string) => `/g/${encodeSegment(name)}`,
  groupSetting: (group: string) => `/group-setting/${encodeSegment(group)}`,
  pages: "/pages",
  suggestedPages: "/suggested-pages",
  likedPages: "/liked-pages",
  createPage: "/create-page",
  pageDetail: (name: string) => `/p/${encodeSegment(name)}`,
  pageSetting: (page: string) => `/page-setting/${encodeSegment(page)}`,
  messages: "/messages",
  profile: (username: string) => `/@${encodeSegment(username)}`,
  settings: "/setting",
  settingsPage: (page: string) => `/setting/${encodeSegment(page)}`,
  wallet: "/wallet",
  withdrawal: "/withdrawal",
  deals: "/deals",
  findFriends: "/find-friends",
  trending: "/trending",
} as const

export const apiRoutes = {
  auth: {
    me: "auth/me",
    login: "auth/login",
    register: "auth/register",
    confirmLogin: "auth/confirm-login",
    confirmAccount: "auth/confirm-account",
    forgotPassword: "auth/forgot-password",
    confirmResetSms: "auth/confirm-reset-sms",
    resetPassword: "auth/reset-password",
  },
  profile: {
    byUsername: (username: string) => `profile/${encodeSegment(username)}`,
  },
  checkout: {
    snapshot: "checkout/snapshot",
    address: "checkout/address",
    submit: "checkout/submit",
  },
  orders: {
    list: "orders",
    detail: (id: string | number) => `orders/${encodeSegment(id)}`,
    received: (id: string | number) => `orders/${encodeSegment(id)}/received`,
  },
  customerOrders: {
    detail: (id: string | number) => `customer-orders/${encodeSegment(id)}`,
    status: (id: string | number) => `customer-orders/${encodeSegment(id)}/status`,
  },
  messages: {
    conversations: "messages/conversations",
    detail: (conversationId: string | number) => `messages/${encodeSegment(conversationId)}`,
    send: "messages/send",
  },
} as const

export const backendRoutes = {
  auth: {
    logout: "/index.php?link1=logout",
  },
  session: {
    currentUser: (sessionId?: string) =>
      `/api/v2/endpoints/get-current-user.php${sessionId ? `?session_id=${encodeQueryValue(sessionId)}` : ""}`,
    setBrowserCookie: (accessToken: string) =>
      `/api/v2/endpoints/set-browser-cookie.php?access_token=${encodeQueryValue(accessToken)}`,
  },
} as const
