// English description: Centralized route constants for frontend pages, Nuxt API routes, and backend PHP paths.

const encodeSegment = (value: string | number) => encodeURIComponent(String(value))
const encodeQueryValue = (value: string | number) => encodeURIComponent(String(value))

export const appRoutes = {
  home: "/",
  feed: "/home",
  adminCp: "/admin-cp",
  welcome: "/welcome",
  register: "/register",
  forgotPassword: "/forgot-password",
  termsOfUse: "/terms/terms",
  privacyPolicy: "/terms/privacy-policy",
  confirmLogin: "/confirm-login",
  resetPassword: "/reset-password",
  confirmAccount: "/confirm-account",
  confirmResetSms: "/confirm-reset-sms",
  logout: "/logout",
  explore: "/explore",
  hashtag: (tag: string) => `/hashtag/${encodeSegment(tag)}`,
  blogs: "/blogs",
  createBlog: "/create-blog",
  readBlog: (slug: string) => `/read-blog/${encodeSegment(slug)}`,
  popular: "/popular",
  savedPosts: "/saved-posts",
  reels: "/reels",
  watch: "/watch",
  photos: "/photos",
  movies: "/movies",
  memories: "/memories",
  search: "/search",
  statusCreate: "/status/create",
  products: "/products",
  newProduct: "/new-product",
  editProduct: (id: string | number) => `/edit-product/${encodeSegment(id)}`,
  myProducts: "/my-products",
  directory: "/directory",
  forum: "/forum",
  games: "/games",
  goPro: "/go-pro",
  live: "/live",
  poke: "/poke",
  checkout: "/checkout",
  orders: "/orders",
  orderDetail: (id: string | number) => `/order/${encodeSegment(id)}`,
  customerOrder: (id: string | number) => `/customer_order/${encodeSegment(id)}`,
  jobs: "/jobs",
  funding: "/funding",
  createFunding: "/create_funding",
  showFund: (id: string | number) => `/show_fund/${encodeSegment(id)}`,
  events: "/events",
  createEvent: "/events/create-event",
  eventDetail: (id: string | number) => `/events/${encodeSegment(id)}`,
  groups: "/groups",
  suggestedGroups: "/suggested-groups",
  joinedGroups: "/joined_groups",
  createGroup: "/create-group",
  groupDetail: (name: string) => `/g/${encodeSegment(name)}`,
  groupSetting: (group: string) => `/group-setting/${encodeSegment(group)}`,
  pages: "/pages",
  suggestedPages: "/suggested-pages",
  likedPages: "/liked-pages",
  createPage: "/create-page",
  pageDetail: (name: string) => `/p/${encodeSegment(name)}`,
  pageSetting: (page: string) => `/page-setting/${encodeSegment(page)}`,
  messages: "/messages",
  profile: (username: string) => `/@${encodeSegment(username)}`,
  settings: "/setting",
  settingsPage: (page: string) => `/setting/${encodeSegment(page)}`,
  wallet: "/wallet",
  withdrawal: "/withdrawal",
  deals: "/deals",
  findFriends: "/find-friends",
  trending: "/trending",
} as const

export const apiRoutes = {
  auth: {
    me: "auth/me",
    login: "auth/login",
    register: "auth/register",
    confirmLogin: "auth/confirm-login",
    confirmAccount: "auth/confirm-account",
    forgotPassword: "auth/forgot-password",
    confirmResetSms: "auth/confirm-reset-sms",
    resetPassword: "auth/reset-password",
  },
  profile: {
    byUsername: (username: string) => `profile/${encodeSegment(username)}`,
  },
  feed: {
    home: "feed/home",
    saved: "feed/saved",
    explore: "feed/explore",
    hashtag: (tag: string) => `feed/hashtag/${encodeSegment(tag)}`,
    popular: "feed/popular",
    videos: "feed/videos",
    photos: "feed/photos",
    memories: "feed/memories",
    poke: "feed/poke",
    posts: {
      create: "feed/posts/create",
      action: "feed/posts/action",
    },
    comments: {
      action: "feed/comments/action",
      replies: "feed/comments/replies",
    },
    stories: {
      create: "feed/stories/create",
      action: "feed/stories/action",
    },
  },
  events: {
    catalog: "events",
    detail: (id: string | number) => `events/${encodeSegment(id)}`,
    posts: (id: string | number) => `events/${encodeSegment(id)}/posts`,
    create: "events/create",
    going: (id: string | number) => `events/${encodeSegment(id)}/going`,
    interested: (id: string | number) => `events/${encodeSegment(id)}/interested`,
    attendees: (id: string | number) => `events/${encodeSegment(id)}/attendees`,
  },
  blogs: {
    list: "blogs",
    create: "blogs/create",
  },
  community: {
    groups: "community/groups",
    groupBySlug: (slug: string) => `community/groups/${encodeSegment(slug)}`,
    groupJoin: (slug: string) => `community/groups/${encodeSegment(slug)}/join`,
    pages: "community/pages",
    pageBySlug: (slug: string) => `community/pages/${encodeSegment(slug)}`,
    pageById: (id: number | string) => `community/pages/id/${encodeSegment(id)}`,
    pagePosts: (slug: string) => `community/pages/${encodeSegment(slug)}/posts`,
    pageFollow: (slug: string) => `community/pages/${encodeSegment(slug)}/follow`,
    groupById: (id: number | string) => `community/groups/id/${encodeSegment(id)}`,
  },
  checkout: {
    snapshot: "checkout/snapshot",
    address: "checkout/address",
    submit: "checkout/submit",
  },
  orders: {
    list: "orders",
    detail: (id: string | number) => `orders/${encodeSegment(id)}`,
    received: (id: string | number) => `orders/${encodeSegment(id)}/received`,
  },
  customerOrders: {
    detail: (id: string | number) => `customer-orders/${encodeSegment(id)}`,
    status: (id: string | number) => `customer-orders/${encodeSegment(id)}/status`,
  },
  messages: {
    conversations: "messages/conversations",
    thread: "messages/thread",
    multi: "messages/multi",
    send: "messages/send",
  },
  navigation: {
    general: "navigation/general",
  },
  search: {
    index: "search",
  },
  settings: {
    me: "settings/me",
    update: "settings/update",
    sessions: "settings/sessions",
    blocked: "settings/blocked",
    unblock: "settings/unblock",
    myInfo: "settings/my-info",
  },
} as const

export const backendRoutes = {
  auth: {
    logout: "/index.php?link1=logout",
  },
  api: {
    auth: "auth",
    createAccount: "create-account",
    sendResetPasswordEmail: "send-reset-password-email",
    sendResetPasswordSms: "send-reset-password-sms",
    resetPassword: "reset_password",
    twoFactor: "two-factor",
    activeAccountSms: "active_account_sms",
    confirmResetPasswordSms: "confirm-reset-password-sms",
    search: "search",
    generalData: "get-general-data",
    userData: "get-user-data",
    updateUserData: "update-user-data",
  },
  session: {
    currentUser: (sessionId?: string) =>
      `/api/v2/endpoints/get-current-user.php${sessionId ? `?session_id=${encodeQueryValue(sessionId)}` : ""}`,
    setBrowserCookie: "/api/v2/endpoints/set-browser-cookie.php",
  },
  web: {
    requests: "/requests.php",
  },
} as const
