name: Deploy production

on:
  push:
    branches:
      - main

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            export PATH="/root/.local/share/pnpm/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

			      echo "node=$(node -v)"
			      echo "pnpm=$(/root/.local/share/pnpm/bin/pnpm -v)"
            
            DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"

            echo "==> Go to project"
            cd "$DEPLOY_PATH"

            echo "==> Save current commit for rollback"
            git rev-parse HEAD > /home/vnseea/last_deploy_commit.txt || true

            echo "==> Pull latest main"
            git fetch origin main
            git reset --hard origin/main

            echo "==> Restart PHP-FPM"
            systemctl restart php8.3-fpm

            echo "==> Build Nuxt client"
            cd "$DEPLOY_PATH/client"

            pm2 stop vnseea-client || pm2 stop 2 || true

            rm -rf .output .nuxt node_modules/.vite

            /root/.local/share/pnpm/bin/pnpm install --frozen-lockfile
		        /root/.local/share/pnpm/bin/pnpm build

            test -f .output/server/index.mjs

            echo "==> Restart PM2"
            pm2 restart vnseea-client --update-env || pm2 restart 2 --update-env
            pm2 restart vnseea-realtime --update-env || pm2 restart 1 --update-env
            pm2 save

            echo "==> Reload Nginx"
            nginx -t
            systemctl reload nginx

            echo "==> Smoke test"
            curl -I http://127.0.0.1:3000/home || true
            curl -I https://v2.vnseea.vn/home || true

            echo "==> Deploy done"
